import numpy as np
import pandas as pd

def create_sequences(data: np.ndarray, seq_length: int = 24) -> tuple[np.ndarray, np.ndarray]:
    """
    Creates input/target sequence pairs for LSTM from a 1D time series array.
    """
    xs, ys = [], []
    for i in range(len(data) - seq_length):
        xs.append(data[i:i + seq_length])
        ys.append(data[i + seq_length])
    return np.array(xs), np.array(ys)

def engineer_features(df: pd.DataFrame, timestamp_col: str = 'timestamp', value_col: str = 'pcu_value') -> pd.DataFrame:
    """
    Creates all XGBoost features from the raw dataframe.
    Features: hour, day_of_week, is_weekend, rolling_mean, lag, diff, etc.
    """
    df = df.copy()
    df[timestamp_col] = pd.to_datetime(df[timestamp_col])
    
    # Time-based features
    df['hour'] = df[timestamp_col].dt.hour
    df['day_of_week'] = df[timestamp_col].dt.dayofweek
    df['is_weekend'] = df['day_of_week'].isin([5, 6]).astype(int)
    
    # Peak hour flag (8-10 AM, 5-7 PM)
    df['is_peak_hour'] = df['hour'].isin([8, 9, 10, 17, 18, 19]).astype(int)
    
    # Rolling features (assumes 5-minute intervals)
    df['rolling_mean_1h'] = df[value_col].rolling(window=12, min_periods=1).mean()
    df['rolling_std_1h'] = df[value_col].rolling(window=12, min_periods=1).std().fillna(0)
    df['rolling_mean_3h'] = df[value_col].rolling(window=36, min_periods=1).mean()
    
    # Lag features
    df['lag_1h'] = df[value_col].shift(12)
    df['lag_2h'] = df[value_col].shift(24)
    df['lag_24h'] = df[value_col].shift(288)
    
    # Difference features
    df['diff_1'] = df[value_col].diff(1)
    df['diff_12'] = df[value_col].diff(12)
    
    # Fill NA values generated by shifts and rolling calculations
    df.ffill(inplace=True)
    df.bfill(inplace=True)
    df.fillna(0, inplace=True)
    
    return df

def normalize_data(data: np.ndarray) -> tuple[np.ndarray, float, float]:
    """
    Min-max normalize data to [0, 1].
    """
    min_val = np.min(data)
    max_val = np.max(data)
    if max_val == min_val:
        return np.zeros_like(data), float(min_val), float(max_val)
    normalized = (data - min_val) / (max_val - min_val)
    return normalized, float(min_val), float(max_val)

def denormalize_data(data: np.ndarray, min_val: float, max_val: float) -> np.ndarray:
    """
    Denormalize data from [0, 1] back to original scale.
    """
    return data * (max_val - min_val) + min_val
